/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Laundry;

import Laundry.Dashboard;
import javax.swing.JOptionPane;

/**
 *
 * @author Fancysx
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public int loginAttempts = 0;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        usericon = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        underlinename = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        underlinename1 = new javax.swing.JLabel();
        disablepw = new javax.swing.JLabel();
        showpw = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(31, 142, 140));

        Right.setBackground(new java.awt.Color(251, 251, 251));
        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 142, 140));
        jLabel1.setText("LAUNDRY");
        Right.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, 50));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Password");
        Right.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 70, 20));

        Password.setBackground(new java.awt.Color(251, 251, 251));
        Password.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Password.setBorder(null);
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Right.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 290, 20));

        usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/user_cvt.png"))); // NOI18N
        Right.add(usericon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 30, 40));

        Name.setBackground(new java.awt.Color(251, 251, 251));
        Name.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Name.setBorder(null);
        Name.setMargin(new java.awt.Insets(2, 7, 2, 7));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Right.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 290, 20));

        underlinename.setText("________________________________________________");
        Right.add(underlinename, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 20));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Username");
        Right.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 80, 20));

        logbtn.setBackground(new java.awt.Color(31, 142, 140));
        logbtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        logbtn.setForeground(new java.awt.Color(255, 255, 255));
        logbtn.setText("LOGIN");
        logbtn.setFocusPainted(false);
        logbtn.setHideActionText(true);
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });
        Right.add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 390, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/home-button.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Right.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 60, 50));

        underlinename1.setText("________________________________________________");
        Right.add(underlinename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        disablepw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/hidden_cvt.png"))); // NOI18N
        disablepw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disablepw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disablepwMouseClicked(evt);
            }
        });
        Right.add(disablepw, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 30, 40));

        showpw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/eye_cvt.png"))); // NOI18N
        showpw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpwMouseClicked(evt);
            }
        });
        Right.add(showpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/logomenu-removebg-preview.png"))); // NOI18N
        Right.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 210));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 142, 140));
        jLabel4.setText("WELCOME TO VOINX");
        Right.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 989, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Right, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed
        // System.out.print("Sign up Btn clicked!");
        if(Name.getText().equals("Isfahan Kaefal") && Password.getText().equals("admin")) {
            setVisible(false);
            Dashboard DashboardFrame = new Dashboard();
            DashboardFrame.setVisible(true);
            DashboardFrame.pack();
            DashboardFrame.setLocationRelativeTo(null); 
            this.dispose();
        } else {
            loginAttempts++; // Tambahkan counter setiap kali login gagal
            if (loginAttempts >= 3) {
                JOptionPane.showMessageDialog(null, "Anda telah mencapai batas percobaan login. Aplikasi akan ditutup.");
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Username or Password. Percobaan tersisa:  " + (3 - loginAttempts));
            }
        }
    }//GEN-LAST:event_logbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void disablepwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disablepwMouseClicked
        // TODO add your handling code here:
        Password.setEchoChar((char)0);
        disablepw.setVisible(false);
        disablepw.setEnabled(false);
        showpw.setEnabled(true);
        showpw.setEnabled(true);
    }//GEN-LAST:event_disablepwMouseClicked

    private void showpwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpwMouseClicked
        // TODO add your handling code here:
        Password.setEchoChar((char)8226);
        disablepw.setVisible(true);
        disablepw.setEnabled(true);
        showpw.setEnabled(false);
        showpw.setEnabled(false);
    }//GEN-LAST:event_showpwMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel disablepw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logbtn;
    private javax.swing.JLabel showpw;
    private javax.swing.JLabel underlinename;
    private javax.swing.JLabel underlinename1;
    private javax.swing.JLabel usericon;
    // End of variables declaration//GEN-END:variables
}
